language: python
python:
  - "3.5.2"
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run test
script:
  - export FLASK_APP=manage.py
  - export FLASK_ENV='development'
  - flask test app
  - flask test models