"""empty message

Revision ID: 095dc0221236
Revises: 62452ae49ab6
Create Date: 2018-05-22 18:49:22.669988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '095dc0221236'
down_revision = '62452ae49ab6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    # ### end Alembic commands ###
